api/urls.py
from django.urls import path
from .views import (LoginView, CreateUserView, VerificationView,
                    EventListView, SocietyListView, EventView,
                    SocietyView, TagEventsView, TagListView, SocietyEventsView,
                    SocietyPastEventsView, UpcomingEventListView, PastEventListView,
                    ResendOTPView, ForgotView)

app_name = 'api'

urlpatterns = [
    path('auth/login', LoginView.as_view(), name="login"),

    path('auth/register', CreateUserView.as_view(), name="register"),

    path('auth/verify', VerificationView.as_view(), name="verify"),

    path('auth/resend', ResendOTPView.as_view(), name="resend"),

    path('auth/forgot', ForgotView.as_view(), name="reset"),

    path('event/<int:pk>', EventView.as_view(), name="event"),

    path('society/<int:pk>', SocietyView.as_view(), name="society"),

    path('tag/<int:pk>/events', TagEventsView.as_view(),
         {"current": False}, name="tag_events"),

    path('tag/<int:pk>/events/current', TagEventsView.as_view(),
         {"current": True}, name="tag_events_current"),

    path('society/<int:pk>/events', SocietyEventsView.as_view(),
         {"period": ""}, name="society_events"),

    path('society/<int:pk>/events/current', SocietyEventsView.as_view(),
         {"period": "current"}, name="society_events_current"),

    path('society/<int:pk>/events/past', SocietyPastEventsView.as_view(),
         name="society_events_past"),

    path('society/<int:pk>/events/upcoming', SocietyEventsView.as_view(),
         {"period": "upcoming"}, name="society_events_upcoming"),

    path('events/past', PastEventListView.as_view(), name="events_past"),

    path('events/upcoming', UpcomingEventListView.as_view(),
         {"limit": None}, name="events_upcoming"),

    path('events/upcoming/<int:limit>',
         UpcomingEventListView.as_view(), name="events_upcoming_limit"),

    path('events', EventListView.as_view(), name="events"),

    path('societys', SocietyListView.as_view(), name="societies"),

    path('tags', TagListView.as_view(), name="tags"),
]

dashboard/urls.py
from django.urls import path, include
from .views import HomeView, UpdateEventView, CreateUserView, CreateEventView, SendNotificationView, NotificationSuccessView

app_name = 'dashboard'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('event/create', CreateEventView.as_view(), name="create_event"),
    path('event/update/<int:pk>', UpdateEventView.as_view(), name="update_event"),
    path('notification', SendNotificationView.as_view(), name="notification"),
    path('notification/success', NotificationSuccessView.as_view(),
         name="success_notification"),
    path('accounts/signup', CreateUserView.as_view(), name="signup"),
]

eventoapi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dashboard.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Evento</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans" rel="stylesheet">
    <!-- <link rel="stylesheet" href="{% static 'css/styles.css' %}"> -->
    <style>
   :root {
    --primary-color: #7E55E4;
    --secondary-color: #A357EB;
    --shadow-color: #E0DAED
}

body {
    font-family: 'Nunito Sans', sans-serif;
    margin: .5rem;
}

a {
    color: var(--primary-color)
}

a:hover {
    color: var(--secondary-color)
}

.navbar-brand {
    box-shadow: inset 0 -5px white;
    font-weight: 600;
    letter-spacing: 2px;
}
.dropdown-menu {
    right: 0;
    left:unset;
}

.nav-link {
    color: #fff !important
}

.card {
    box-shadow: 1px 1px 20px 0px #dcdcdc;
    border: 0;
    border-radius: 8px;
}

.btn-primary {
    background: var(--primary-color);
    border-color: var(--primary-color)
}

.btn-primary:hover {
    background-color: var(--secondary-color);
    border-color: var(--secondary-color)
}

.btn-primary:active {
    background-color: var(--secondary-color) !important;
    border-color: var(--secondary-color) !important
}

.btn-primary:focus,
.form-control:focus {
    border-color: var(--secondary-color);
    box-shadow: 0 0 0 0.2rem var(--shadow-color) !important;
}

.form-control {
    border-color: var(--shadow-color)
}

.dropdown-item:active {
    background-color: var(--primary-color);
}

header {
    background-color: #e9ecef;
}

.dateinput,
.timeinput {
    width: 50%;
    display: inline-block;
}

.login-box {
    max-width: 300px;
}

.signup-box {
    max-width: 450px;
}

.form-box {
    max-width: 500px;
}
    </style>

<body>


    <div class="container p-0">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded p-3">
            <a class="navbar-brand uppercase font-bold" href="/">EVENTO</a>

            <button class="navbar-toggler" type="button" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse" id="navbar">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            {{ user.name }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="display:none">
                            <a class="dropdown-item" href="{% url 'password_change' %}">
                                Change password
                            </a>
                            <a class="dropdown-item" href="{% url 'logout' %}">
                                Logout
                            </a>
                        </div>
                    </li>
                    {% else %}

                    <form class="form-inline">
                        <a class="btn mx-2 btn-primary" href="{% url 'dashboard:signup' %}">Sign up</a>
                        <a class="btn mx-2 btn-outline-light" href="{% url 'login' %}">Log in</a>
                    </form>

                    {% endif %}

                </ul>
            </div>
        </nav>

        {% block content %} {% endblock %}
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {

            document.querySelector('.navbar-toggler').addEventListener("click", function (e) {
                var navbar = document.querySelector('#navbar');
                if (navbar.classList == "navbar-collapse collapse")
                    navbar.classList += " show";
                else
                    navbar.classList = "navbar-collapse collapse"

            }, false);

            document.querySelector("#navbarDropdown").addEventListener("click", function (e) {
                var dropdown = document.querySelector(".dropdown-menu");
                if (dropdown.style.display == "none")
                    dropdown.style.display = "block";
                else
                    dropdown.style.display = "none";

            }, false);


        }, false);
    </script>

</body>

</html>