api/urls.py
from django.urls import path
from .views import (LoginView, CreateUserView, VerificationView,
                    EventListView, SocietyListView, EventView,
                    SocietyView, TagEventsView, TagListView, SocietyEventsView,
                    SocietyPastEventsView, UpcomingEventListView, PastEventListView,
                    ResendOTPView, ForgotView)

app_name = 'api'

urlpatterns = [
    path('auth/login', LoginView.as_view(), name="login"),

    path('auth/register', CreateUserView.as_view(), name="register"),

    path('auth/verify', VerificationView.as_view(), name="verify"),

    path('auth/resend', ResendOTPView.as_view(), name="resend"),

    path('auth/forgot', ForgotView.as_view(), name="reset"),

    path('event/<int:pk>', EventView.as_view(), name="event"),

    path('society/<int:pk>', SocietyView.as_view(), name="society"),

    path('tag/<int:pk>/events', TagEventsView.as_view(),
         {"current": False}, name="tag_events"),

    path('tag/<int:pk>/events/current', TagEventsView.as_view(),
         {"current": True}, name="tag_events_current"),

    path('society/<int:pk>/events', SocietyEventsView.as_view(),
         {"period": ""}, name="society_events"),

    path('society/<int:pk>/events/current', SocietyEventsView.as_view(),
         {"period": "current"}, name="society_events_current"),

    path('society/<int:pk>/events/past', SocietyPastEventsView.as_view(),
         name="society_events_past"),

    path('society/<int:pk>/events/upcoming', SocietyEventsView.as_view(),
         {"period": "upcoming"}, name="society_events_upcoming"),

    path('events/past', PastEventListView.as_view(), name="events_past"),

    path('events/upcoming', UpcomingEventListView.as_view(),
         {"limit": None}, name="events_upcoming"),

    path('events/upcoming/<int:limit>',
         UpcomingEventListView.as_view(), name="events_upcoming_limit"),

    path('events', EventListView.as_view(), name="events"),

    path('societys', SocietyListView.as_view(), name="societies"),

    path('tags', TagListView.as_view(), name="tags"),
]

dashboard/urls.py
from django.urls import path, include
from .views import HomeView, UpdateEventView, CreateUserView, CreateEventView, SendNotificationView, NotificationSuccessView

app_name = 'dashboard'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('event/create', CreateEventView.as_view(), name="create_event"),
    path('event/update/<int:pk>', UpdateEventView.as_view(), name="update_event"),
    path('notification', SendNotificationView.as_view(), name="notification"),
    path('notification/success', NotificationSuccessView.as_view(),
         name="success_notification"),
    path('accounts/signup', CreateUserView.as_view(), name="signup"),
]

eventoapi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.index_title = settings.ADMIN_INDEX_TITLE
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dashboard.urls')),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone
from django import forms
from api.models import Event, Society
from .firebase import send_notification_to_user, send_notification_to_all
User = get_user_model()


EVENT_FIELDS = ['name', 'start_day', 'end_day',
                'notes', 'image', 'contact_person', 'contact_number',
                'session', 'venue', 'registration_link']


class SignUpForm(UserCreationForm):
    society = forms.ModelChoiceField(
        queryset=Society.objects.all(), required=True)

    class Meta:
        model = User
        fields = ['email', 'name', 'phone', 'society',
                  'password1', 'password2']


class EventForm(forms.ModelForm):
    start_day = forms.SplitDateTimeField(
        widget=forms.SplitDateTimeWidget(
            date_attrs={'type': 'date', 'class': 'form-control'},
            time_attrs={'type': 'time', 'class': 'form-control'}
        )
    )
    end_day = forms.SplitDateTimeField(
        widget=forms.SplitDateTimeWidget(
            date_attrs={'type': 'date', 'class': 'form-control'},
            time_attrs={'type': 'time', 'class': 'form-control'}
        )
    )

    class Meta:
        model = Event
        fields = EVENT_FIELDS
        labels = {
            "image": "Poster",
            "start_day": "Start Date and Time",
            "end_day": "End Date and Time"
        }

class NotificationForm(forms.Form):
    # recipient = forms.CharField(label='Send to', max_length=100)
    title = forms.CharField(label='Title', max_length=30)
    message = forms.CharField(widget=forms.Textarea, label='Message', max_length=100)

    def send_notification(self):
        # user = User.objects.get(email=self.cleaned_data["recipient"])
        send_notification_to_all(self.cleaned_data)

dashboard/views.py
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import redirect_to_login
from django.utils import timezone

from api.models import Event, Society
from .forms import SignUpForm, EventForm, NotificationForm


class SocietyAdminAccessMixin(UserPassesTestMixin):
    login_url = '/accounts/login/'

    def test_func(self):
        return self.request.user.role == "1"

    def handle_no_permission(self):
        return redirect_to_login(self.request.get_full_path(), self.login_url)


class HomeView(LoginRequiredMixin, SocietyAdminAccessMixin, ListView):
    model = Event
    template_name = "dashboard/home.html"

    def get_queryset(self):
        society = self.request.user.society
        return Event.objects.filter(society=society).order_by('-start_day')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = timezone.now()
        return context


class CreateEventView(LoginRequiredMixin, SocietyAdminAccessMixin, CreateView):
    model = Event
    template_name = "dashboard/create_event.html"
    form_class = EventForm
    success_url = "/"

    def form_valid(self, form):
        form.instance.creater = self.request.user
        form.instance.society = self.request.user.society
        return super().form_valid(form)


class UpdateEventView(LoginRequiredMixin, SocietyAdminAccessMixin, UpdateView):
    model = Event
    template_name = "dashboard/update_event.html"
    form_class = EventForm
    success_url = "/"


class CreateUserView(CreateView):
    template_name = "registration/signup.html"
    form_class = SignUpForm
    success_url = "/"

    def form_valid(self, form):
        form.instance.role = '1'
        return super().form_valid(form)


class SendNotificationView(LoginRequiredMixin, SocietyAdminAccessMixin, FormView):
    template_name = "dashboard/notification.html"
    form_class = NotificationForm
    success_url = "/notification/success"

    def form_valid(self, form):
        form.send_notification()
        return super().form_valid(form)


class NotificationSuccessView(TemplateView):
    template_name = "dashboard/not_success.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

templates/dashboard/create_event.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="card form-box mx-auto mt-4 mb-5 p-4">
    <h3 class="mb-4">Create Event</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Create">
    </form>
</div>
{% endblock %}

templates/dashboard/home.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}


<header class="d-sm-flex flex-row justify-content-between mt-4 p-3 rounded text-center ">
        <h4 class="m-0 pt-1 text-sm-left">{{ user.society }} - Events</h4>
        <div class="mt-3 mt-sm-0">
            {% if user.is_superuser %}
                <a class="btn btn-primary m-1" role="button" href="{% url 'dashboard:notification' %}">Send Notification</a>
            {% endif %}
            <a class="btn btn-primary m-1" role="button" href="{% url 'dashboard:create_event' %}">Create Event</a>
        </div>

</header>

<main class="mt-4">
    {% for event in object_list %}
    <div class="bg-light p-3 my-2">
        <a class="font-weight-bold" href="{% url 'dashboard:update_event' event.id %}">{{ event.name }}</a> -
        {% if event.start_day > today %}
        <span class="text-muted">Starts {{ event.start_day|naturaltime }}.</span>
        {% else %}
        <span class="text-muted">Ended {{ event.start_day|naturaltime }}.</span>
        {% endif %}
    </div>
    {% endfor %}
</main>
{% endblock %}

templates/dashboard/not_success.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="card form-box mx-auto mt-4 mb-5 p-4">
    Success
</div>
{% endblock %}

templates/dashboard/notification.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="card form-box mx-auto mt-4 mb-5 p-4">
    <h3 class="mb-4">Send Notification</h3>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Send">
    </form>
</div>
{% endblock %}

templates/dashboard/update_event.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card form-box mx-auto mt-4 mb-5 p-4">
    <h3 class="mb-4">Edit Event</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Save">
    </form>
</div>
{% endblock %}